[".config/vim"]
    type = "git-repo"
    url = "https://github.com/mklimuk/nvim-config.git"
    refreshPeriod = "168h"

[".local/share/zsh/completions/_eza"]
    refreshPeriod = "168h"
    type          = "file"
    url           = "https://raw.githubusercontent.com/eza-community/eza/main/completions/zsh/_eza"

