[window]
opacity = 0.7
blur = true

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "MesloLGS NF"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font]
size = 13
