[packages.apt]
    to_remove = ["btop", "htop"]
    [packages.apt.common]
        packages = [
            "apt-transport-https",
            "bat",                 # cat with syntax highlighting and Git integration
            "curl",
            "dnsutils",
            "fd-find",
            "figlet",
            "fzf",
            "git",
            "git-extras",
            "gnupg",
            "gpg",
            "jq",
            "logrotate",
            "lolcat",
            "mc",                  # Midnight Commander
            "ncdu",                # NCurses Disk Usage
            "needrestart",
            "net-tools",
            "openssh-server",
            "p7zip-full",
            "ripgrep",             # search tool like grep and the silver searcher
            "sudo",
            "tzdata",
            "unzip",
            "wget",
            "zsh"
        ]
    [packages.apt.dev_computer]
        packages = []
    [packages.apt.homelab_member]
        packages = ["firmware-misc-nonfree", "ethtool", "lshw", "iperf"]
    [packages.apt.personal_computer]
        packages = []
[packages.homebrew]
    to_remove = ["btop", "htop", "istat-menus", "qlimagesize", "rocket", "shotrr"]
    [packages.homebrew.common]
        casks = [
            "font-departure-mono",
            "font-jetbrains-mono-nerd-font",
            "font-meslo-lg-dz",
            "font-meslo-lg-nerd-font",
            "ghostty",
            "git-credential-manager",
            "grandperspective",              # Disk usage visualizer
            "iterm2",                        # Terminal emulator
            "jordanbaird-ice",               # Menu bar customization
            "lingon-x",
            "orbstack",                      # Docker replacement
            "tailscale",
            "visual-studio-code"
        ]
        formulae = [
            "atuin",           # Better shell history
            "bash",
            "bash-completion",
            "bat",             # cat with syntax highlighting and Git integration
            "bottom",          # Process/system monitor for the terminal.
            "chezmoi",         # Dotfile manager
            "coreutils",
            "eza",             # ls replacement
            "fd",              # fd-find
            "findutils",       # GNU find, locate, updatedb, and xargs
            "fzf",             # Fuzzy finder
            "gawk",            # GNU awk
            "git",
            "git-delta",       # https://github.com/dandavison/delta
            "gnu-sed",         # GNU implementation of the famous stream editor
            "gnu-tar",         # GNU version of the tar archiving utility
            "gnutls",          # GNU Transport Layer Security (TLS) Library
            "gping",           # Ping, but with a graph
            "grep",
            "jq",              # Lightweight and flexible command-line JSON processor
            "mas",             # Mac App Store command-line interface
            "mc",              # Midnight Commander
            "most",            # Pager
            "nano",
            "ncdu",            # NCurses Disk Usage
            "ncurses",         # Text-based UI library
            "openssl",         # SSL/TLS cryptography library
            "rip2",            # A safer, rust-based rm
            "ripgrep",         # search tool like grep and the silver searcher
            "sqlite3",
            "ssh-copy-id",     # Add a public key to a remote machine's authorized_keys file
            "tealdeer",        # TLDR man pages
            "tree",            # Display directories as trees (with optional color/HTML output)
            "vivid",           # https://github.com/sharkdp/vivid
            "wget",
            "zoxide",          # A faster way to navigate your filesystem
            "zsh"
        ]
    [packages.homebrew.dev_computer]
        casks = [
            "bruno",
            "dbeaver-community",
            "fork",
            # "sourcetree", # Alternative to fork
            "cursor",
            "lingon-x",
        ]
        formulae = [
            "act",        # runs GitHub Actions locally
            "bats-core",
            "doggo",      # DNS Client
            "gh",         # GitHub CLI
            "git-delta",
            "git-extras",
            "goaccess",
            "gpg",
            "jless",      # JSON viewer
            "lazygit",    # simple terminal UI for git commands
            "libpq",      # PostgreSQL utilities but not postgresql itself
            "shellcheck",
            "shfmt"
        ]
    [packages.homebrew.homelab_member]
        casks    = []
        formulae = ["ffmpeg", "iperf", "nmap", "tailspin", "pulseaudio"]
    [packages.homebrew.personal_computer]
        casks = [
            "arc",
            "discord",
            "fmail3",
            "google-chrome",
            "chromium",
            "iina",
            "kap",
            "lulu",          # Firewall
            "mimestream",
            "obsidian",
            "raycast",
            "slack",
            "stats",
            "tripmode",
            "whatsapp",
            "zoom",
        ]
        formulae = []